### ISSUE TITLE
Don't use prod API

### ISSUE THREAD

**Issue by cubap** [oss-slu/TPEN-interfaces#26]
https://github.com/oss-slu/TPEN-interfaces/blob/5ec1987c86eb549c2c38056469f78c1fbf5278c0/components/classroom/fetchData.mjs#L9

https://github.com/oss-slu/TPEN-interfaces/blob/870c61952e09aefcd5c277d2e1b7900de78e376a/components/classroom/main.js#L5

Found a couple places `dev.` was missing.
This will get easier as we bring in the TPEN class with these constants in it

**Comment by cubap** [comment]
On the `connecting_Api` branch... my links above might only point on `main`.

**Comment by MutyaSowmya123** [comment]
https://github.com/oss-slu/TPEN-interfaces/commit/ed57ba3d29970633a80f8e111f8def23e6951243
updated in [TPEN-interfaces/components/classroom/fetchData.mjs](https://github.com/oss-slu/TPEN-interfaces/blob/5ec1987c86eb549c2c38056469f78c1fbf5278c0/components/classroom/fetchData.mjs#L9)
